project_id = "zhiiqdczslrnvlyflmke"

[functions.interview-chat]
verify_jwt = true

[functions.analyze-interview]
verify_jwt = true

[functions.text-to-speech]
verify_jwt = true

[functions.speech-to-text]
verify_jwt = true

[functions.ai21-interview-chat]
verify_jwt = false

[functions.generate-zego-token]
verify_jwt = true

[functions.paystack-payment]
verify_jwt = true

[functions.generate-meeting-minutes]
verify_jwt = true

[functions.process-referral]
verify_jwt = false

[functions.update-user-points]
verify_jwt = false